version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.prod
    command: gunicorn todo_list.wsgi:application --bind 0.0.0.0:8000 --timeout 300
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data:

