version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - INSTALL_POSTGRES_CLIENT=true
    ports:
      - 8000:8000
    env_file:
      - .env.prod.db
    command: gunicorn todo_list.wsgi:application --bind 0.0.0.0:8000 --timeout 300
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  db:
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:



